<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <meta charset="utf-8">
        <?php echo $this->headTitle('App-ball.eu')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/fav.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/weather-icons.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <script src="http://code.highcharts.com/highcharts.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <?php if ($this->username): ?>
                <div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><i class="fa fa-home"></i> Accueil</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="<?php echo $this->url('volley/default', array('controller' => 'event', 'action' => 'add')) ?>"><i class="fa fa-calendar"></i> Nouvel Évènement</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-group"></i> Groupes <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                      <li><a href="/group/add">Nouveau</a></li>
                                      <li><a href="/group/list">Liste de groupes</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/profile"><?php echo $this->username ?></a></li>
                            <li><a href="<?php echo $this->url('volley/auth', array('action' => 'logout')) ?>"><i class="fa fa-sign-out"></i> Déconnexion</a></li>
                        <ul>
                    </div><!--/.nav-collapse -->
                </div>
            <?php endif ?>
        </nav>

        <?php if ($this->flashMessenger()->hasErrorMessages()): ?>
            <div class="fade col-xs-12 col-sm-4 col-sm-offset-4 alert alert-warning alert-dismissible absolute-alerte" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <?php 
              $messages = $this->flashMessenger()->getErrorMessages();
              foreach($messages as $message) {
                  echo $message;
              }
              ?>
            </div>
        <?php endif ?>

        <?php if ($this->flashMessenger()->hasMessages()): ?>
            <div class="fade col-xs-12 col-sm-4 col-sm-offset-4 alert alert-success alert-dismissible absolute-alerte" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <?php 
              $messages = $this->flashMessenger()->getMessages();
              foreach($messages as $message) {
                  echo $message;
              }
              ?>
            </div>
        <?php endif ?>

        <div class="container-fluid">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>

<script type="text/javascript">
    setTimeout(function () {
        $(".alert").addClass("in");
        setTimeout(function () {
            $(".alert").removeClass("in");
        }, 2000);
    }, 0);
</script>
