
        <!-- *** INTRO IMAGE ***
_________________________________________________________ -->
        <div id="intro" class="clearfix">
            <div class="item">
                <div class="container">
                    <div class="row">
                        <div class="carousel-caption">
                            <div data-animate="fadeInDown" class="logo">
                                <div class="icon" style="font-size:11em;"><i class="fa fa-user-md"></i></div>
                                <h1 data-animate="fadeInDown"><br/>Valérie Defour<br/>Ostéopathe</h1>
                            </div>
                            <h2 data-animate="fadeInDown">Bienvenue !</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- *** INTRO IMAGE END *** -->

        <!-- *** ABOUT ***
_________________________________________________________ -->
        <div class="section" id="about">
            <div class="container">
                <div class="row">

                    <div class="col-sm-12">
                        <h2 class="title" data-animate="fadeInDown">À propos</h2>
                    </div>

                    <div class="col-sm-12">

                        <div class="row">
                            <div class="col-sm-6" data-animate="fadeInUp">
                                <img src="img/about.jpg" class="image img-circle img-responsive" alt="This is me - IT worker">
                            </div>

                            <div class="col-sm-6 text-left" data-animate="fadeInUp">

                                <p>
                                Lorem ipsum dolor sit amet, <strong>consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua.</strong> Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                                <p>Lorem ipsum dolor sit amet, <strong>consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua.</strong> Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /#about -->

        <!-- *** ABOUT END *** -->

        <!-- *** REFERENCES IMAGE ***
_________________________________________________________ -->
        <div class="section" id="references">
            <div class="container">
                <div class="col-sm-12">

                    <div class="mb20">
                        <h2 class="title" data-animate="fadeInUp">Pour qui et Quand consulter ?</h2>
                    </div>

                    <div id="detail">

                        <span class="close">&times;</span> 

                        <div class="text-center">
                            <h1 id="detail-title">&nbsp;</h1>
                        </div>

                        <div id="detail-content"></div>

                    </div>
                    <!-- Reference detail -->

                    <div id="references-masonry" data-animate="fadeInUp">

                        <!--  NOURISSON  -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-1.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Nourisson</h3> 
                                        <p>Short project description goes here...</p>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                        <p>
                                            Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                            explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                        </p>

                                        <p>
                                            Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                            explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                        </p>
                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--  ENFANT  -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-5.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Enfant</h3>
                                        <p>Short project description goes here...</p>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                        <p>
                                            Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                            explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                        </p>

                                        <p>
                                            Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                            explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                        </p>
                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--  ENCEINTE -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-2.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Femme enceinte</h3> 
                                        <p>Short project description goes here...</p>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                    <p>
                                        Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                        explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                    </p>

                                    <p>
                                        Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                        explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                    </p>
                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--  ADULTE -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-6.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Adulte</h3>
                                        <p>Short project description goes here...</p>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                    <p>
                                        Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                        explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                    </p>

                                    <p>
                                        Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                        explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                    </p>

                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>

                            </div>
                        </div>

                        <!--  SENIOR -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-3.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Sénior</h3>
                                        <p>Short project description goes here...</p>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                    <p>
                                        Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                        explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                    </p>

                                    <p>
                                        Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                        explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.
                                    </p>

                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>

                            </div>
                        </div>

                        <!--  SPORTIF -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-4.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Sportif</h3> 
                                        <p>Short project description goes here...</p>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                    <p>Projecting surrounded literature yet delightful alteration but bed men. Open are from long why cold. If must snug by upon sang loud left. As me do preference entreaties compliment motionless ye literature. Day behaviour
                                        explained law remainder. Produce can cousins account you pasture. Peculiar delicate an pleasant provided do perceive.</p>

                                    <p>Sitting mistake towards his few country ask. You delighted two rapturous six depending objection happiness something the. Off nay impossible dispatched partiality unaffected. Norland adapted put ham cordial. Ladies
                                        talked may shy basket narrow see. Him she distrusts questions sportsmen. Tolerably pretended neglected on my earnestly by. Sex scale sir style truth ought.</p>

                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /#references-masonry -->

                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.section -->

        <!-- *** REFERENCES END *** -->


        <!-- *** SERVICES ***
_________________________________________________________ -->
        <div class="section text-gradient" id="services">
            <div class="container">
                <div class="col-md-12">
                    <h2 class="title" data-animate="fadeInDown">le cabinet</h2>

                    <!-- SLIDER -->
                    <div class="sr-only img-slider" data-images="img/centre-medical-1.jpg,img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg"></div>
                    <div class="col-md-8 col-md-offset-2">
                        <div id="detail-slider"></div>
                    </div>
                    <!-- SLIDER ENDS -->

                    <div class="row services">

                        <div class="col-md-4" data-animate="fadeInUp">
                            <div class="icon"><i class="fa fa-car"></i>
                            </div>
                            <h3 class="heading">Adresse</h3>
                            <p>
                                Le centre médical se trouve à l'adresse suivante <br/>
                                <span class="time">
                                    <b><i>7 avenue de la Voulzie<br/>
                                    </i></b>
                                </span>
                                <span class="time">
                                    <i><b>77160 Provins</i></b>
                                </span>
                                <br/><br/>
                                Ou aux coordonnées GPS suivante:<br/>
                                <span class="time">
                                    <b><i>48.5500328, 3.2948152</i></b>
                                </span>
                            </p>
                        </div>

                        <div class="col-md-4" data-animate="fadeInUp">
                            <div class="icon"><i class="fa fa-plus-square"></i>
                            </div>
                            <h3 class="heading">Centre médical</h3>
                            <p>
                                Le cabinet est idéalement situé dans le nouveau centre médical de Provins.
                                Ce centre regroupe un grand nombre de professionnel de la santé : Matériel paramédical, Centre de radiologie, Opticien, Audioprothésiste etc.
                            </p>
                        </div>

                        <div class="col-md-4" data-animate="fadeInUp">
                            <div class="icon"><i class="fa fa-clock-o"></i>
                            </div>
                            <h3 class="heading">Horraires</h3>
                            <p>
                                Les consultations ont lieu les:<br/>
                                <i class="fa fa-user-md time"></i> Lundis de <strong>10h à 20h</strong><br/>
                                <i class="fa fa-user-md time"></i> Mardis de <strong>9h à 17h</strong>
                            </p>
                        </div>

                    </div>

                    <!-- <hr> -->

                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.section -->

        <!-- *** SERVICES END *** -->
        <!-- *** MAP ***
_________________________________________________________ -->

        <div class="section" id="map">

        </div>
        <!-- /.section -->

        <!-- *** MAP END *** -->

        <!-- *** CONTACT ***
_________________________________________________________ -->

        <div class="section contact" id="contact" data-animate="fadeInDown">
            <div class="container">
                <div class="col-md-12">


                    <h2 class="title">RDV en ligne</h2>

                    <div class="row">

                        <div class="col-md-8 col-md-offset-2">
                            <form id="contact-form" method="post" action="contact.php">

                                <div class="messages">

                                </div>

                                <div class="controls">

                                    <div class="row">
                                        <div class="col-md-6">
                                            <input type="text" name="name" class="form-control" placeholder="Prénom *" required="required">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" name="surname" class="form-control" placeholder="Nom *" required="required">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" name="phone" class="form-control" placeholder="Téléphone *" required="required">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" name="email" class="form-control" placeholder="Email">
                                        </div>
                                        <div class="col-md-12">
                                            <textarea name="message" class="form-control" placeholder="Message *" rows="4" required="required"></textarea>
                                        </div>
                                        <div class="col-md-12 text-center">
                                            <input type="submit" class="btn btn-primary btn-lg" value="Envoyer">
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>

                    </div>
                    <hr>
                    <h2 class="title">RDV par Téléphone</h2>

                    <div class="row phone">
                        06.06.06.06
                    </div>

                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.section -->

        <!-- *** CONTACT END *** -->

