
        <!-- *** INTRO IMAGE ***
_________________________________________________________ -->
        <div id="intro" class="clearfix">
            <div class="item">
                <div class="container">
                    <div class="row">
                        <div class="carousel-caption">
                            <div data-animate="fadeInDown" class="logo">
                                <div class="icon" style="font-size:10em;"><i class="fa fa-user-md"></i></div>
                                <h1 data-animate="fadeInDown"><br/>Valérie Defour<br/>Ostéopathe</h1>
                            </div>
                            <h2 data-animate="fadeInDown">Bienvenue !</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- *** INTRO IMAGE END *** -->

        <!-- *** ABOUT ***
_________________________________________________________ -->
        <div class="section" id="about">
            <div class="container">
                <div class="row">

                    <div class="col-sm-12">
                        <h2 class="title" data-animate="fadeInDown">À propos</h2>
                    </div>

                    <div class="col-sm-12">

                        <div class="row">
                            <div class="col-sm-6" data-animate="fadeInUp">
                                <img src="img/about.jpg" class="image img-circle img-responsive" alt="This is me - IT worker">
                            </div>

                            <div class="col-sm-6 text-left" data-animate="fadeInUp">

                                <p>An sincerity so extremity he additions. Her yet <strong>there truth merit</strong>. Mrs all projecting favourable now unpleasing. Son law garden chatty temper. Oh children provided to mr elegance marriage strongly. Off can
                                    admiration prosperous now devonshire diminution law.</p>

                                <p>Received overcame oh sensible so at an. Formed do change merely to county it. <strong>Am separate contempt</strong> domestic to to oh. On relation my so addition branched. Put hearing cottage she norland letters equally prepare
                                    too. Replied exposed savings he no viewing as up. Soon body add him hill. No father living really people estate if. Mistake do produce beloved demesne if am pursuit.</p>

                                <p>An sincerity so extremity he additions. Her yet <strong>there truth merit</strong>. Mrs all projecting favourable now unpleasing. Son law garden chatty temper. Oh children provided to mr elegance marriage strongly. Off can
                                    admiration prosperous now devonshire diminution law.</p>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /#about -->

        <!-- *** ABOUT END *** -->

        <!-- *** SERVICES ***
_________________________________________________________ -->
        <div class="section text-gradient" id="services">
            <div class="container">
                <div class="col-md-12">
                    <h2 class="title" data-animate="fadeInDown">Plan accès</h2>

                    <div class="row services">

                        <div class="col-md-5" data-animate="fadeInUp">
                            <div class="icon"><i class="fa fa-car"></i>
                            </div>
                            <h3 class="heading">Adresse</h3>
                            <p>
                                Le centre commercial se trouve à l'adresse suivante <br/>
                                <b><i>7 avenue de la Voulzie<br/>
                                77160 Provins</i></b><br/><br/>
                                Ou aux coordonnées GPS suivante:<br/>
                                <b><i>48.5500328, 3.2948152</i></b>
                            </p>
                        </div>

                        <div class="col-md-5 col-md-offset-1" data-animate="fadeInUp">
                            <div class="icon"><i class="fa fa-plus-square"></i>
                            </div>
                            <h3 class="heading">Centre médical</h3>
                            <p>
                                Le cabinet est idéalement situé dans le nouveau centre médical de Provins.
                                Ce centre regroupe un grand nombre de professionnel de la santé : Matériel paramédical, Centre de radiologie, Opticien, Audioprothésiste etc.
                            </p>
                        </div>

                    </div>

                    <!-- <hr> -->

                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.section -->

        <!-- *** SERVICES END *** -->
        <!-- *** MAP ***
_________________________________________________________ -->

        <div class="section" id="map">

        </div>
        <!-- /.section -->

        <!-- *** MAP END *** -->
        <!-- *** CONTACT ***
_________________________________________________________ -->

        <div class="section contact" id="contact" data-animate="bounceIn">
            <div class="container">
                <div class="col-md-12">


                    <h2 class="title">Demander un RDV</h2>

                    <div class="row">

                        <div class="col-md-8 col-md-offset-2">
                            <form id="contact-form" method="post" action="contact.php">

                                <div class="messages">

                                </div>

                                <div class="controls">

                                    <div class="row">
                                        <div class="col-md-6">
                                            <input type="text" name="name" class="form-control" placeholder="Your firstname *" required="required">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" name="surname" class="form-control" placeholder="Your lastname *" required="required">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" name="email" class="form-control" placeholder="Your email *" required="required">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" name="phone" class="form-control" placeholder="Your phone">
                                        </div>
                                        <div class="col-md-12">
                                            <textarea name="message" class="form-control" placeholder="Message for me *" rows="4" required="required"></textarea>
                                        </div>
                                        <div class="col-md-12 text-center">
                                            <input type="submit" class="btn btn-primary btn-lg" value="Send message">
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>

                    </div>
                    <hr>
                    <h2 class="title">Par Téléphone</h2>

                    <div class="row phone">
                        06.06.06.06
                    </div>

                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.section -->

        <!-- *** CONTACT END *** -->

