<div id="intro" class="clearfix">
    <div class="item">
        <div class="container">
            <div class="row">
                <div class="carousel-caption">
                    <div data-animate="fadeInDown" class="logo">
                        <div class="icon" style="font-size:11em;"><i class="fa fa-user-md"></i></div>
                        <h1 data-animate="fadeInDown"><br/>Valérie Defour<br/>Ostéopathe</h1>
                    </div>
                    <h2 data-animate="fadeInDown"><i class="fa fa-cog fa-spin"></i> Site en construction</h2>
                </div>
            </div>
        </div>
    </div>
</div>