
        <!-- *** INTRO IMAGE ***
_________________________________________________________ -->
        <div id="intro" class="clearfix">
            <div class="item">
                <div class="container">
                    <div class="row">
                        <div class="carousel-caption">
                            <div data-animate="fadeInDown" class="logo">
                                <div class="icon" style="font-size:11em;"><i class="fa fa-user-md"></i></div>
                                <h1 data-animate="fadeInDown"><br/>Valérie Defour<br/>Ostéopathe</h1>
                            </div>
                            <h2 data-animate="fadeInDown">Bienvenue !</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- *** INTRO IMAGE END *** -->

        <!-- *** DEFINITION ***
_________________________________________________________ -->
        <div class="section" id="definition">
            <div class="container">
                <div class="row">

                    <div class="col-sm-12">
                        <h2 class="title" data-animate="fadeInDown">Qu'est ce que l'ostéopathie</h2>
                    </div>

                    <div class="col-sm-12">

                        <div class="row">

                            <div class="col-sm-12 text-left font-up" data-animate="fadeInUp">

                                <p class="lead text-center">
                                    « <strong>L’ostéopathie</strong> vise à diagnostiquer et traiter manuellement les restrictions de mobilité du corps humain qui entraînent des troubles fonctionnels pouvant perturber votre état de santé. 
                                    <strong>L’ostéopathie envisage l’individu dans sa globalité</strong>, en s’appuyant sur une connaissance approfondie de l’anatomie et de la physiologie »
                                </p>
                                <br/>
                                <p>
                                    L'examen ostéopathique vise à trouver la cause du mal du patient. La douleur à un endroit du corps peut être causée par un mauvais équilibrage à un endroit différent. Par exemple une douleur au dos peut résulter d'un problème à la cheville. Par conséquent <strong>l'ostéopathe traite le corps dans son ensemble</strong> quelque soit la raison de la venue du patient afin de proposé un traitement efficace dans la durée. L’ostéopathie est aussi un acte de prévention des troubles fonctionnels du corps humain.
                                </p>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /#about -->

        <!-- *** DEFINITION END *** -->

        <!-- *** WHEN ***
_________________________________________________________ -->

        <div class="section text-gray" id="when" data-animate="fadeInUp">

            <div class="container">
                <div class="col-md-12">

                    <div class="mb20">
                        <h2 class="title" data-animate="fadeInUp">Quand Consulter</h2>

                        <p class="lead text-center" data-animate="fadeInUp">Les bienfaits de l’ostéopathie diverses et variés</p>
                    </div>

                    <ul class="owl-carousel testimonials same-height-row" data-animate="fadeInUp">
                        <li class="item">
                            <div class="testimonial same-height-always">
                                <div class="text">
                                    <h4>Douleurs articulaires et musculaires</h4>
                                    <ul>
                                        <li>Entorses en tout genre</li>
                                        <li>Tendinites</li>
                                        <li>Lumbagos, sciatiques...</li>
                                        <li>Scolioses</li>
                                        <li>Dorsalgies, cervicalgies : torticolis...</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="testimonial same-height-always">
                                <div class="text">
                                    <h4>Système nerveux et vasculaire</h4>
                                    <ul>
                                        <li>Migraines</li>
                                        <li>Névralgies</li>
                                        <li>Lumbagos, sciatiques...</li>
                                        <li>Anxiété, stress</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="testimonial same-height-always">
                                <div class="text">
                                    <h4>Système digestif et viscéral</h4>
                                    <ul>
                                        <li>Troubles de la digestion : constipation, diarrhée...</li>
                                        <li>Troubles génitaux urinaires : menstruations douloureuses, douleurs pendant les rapports...</li>
                                        <li>Troubles ORL : sinusites chroniques, asthme, bronchites chroniques...</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="item">
                            <div class="testimonial same-height-always">
                                <div class="text">
                                    <h4>Séquelles de traumatismes</h4>
                                    <ul>
                                        <li>Accident</li>
                                        <li>Chute sur le crâne, coccyx...</li>
                                        <li>Travail post chirurgical</li>
                                        <li>Entorses et fractures</li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <!-- /.owl-carousel -->
                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->

        </div>
        <!-- /.section -->

        <!-- *** DEFINITION END *** -->

        <!-- *** REFERENCES IMAGE ***
_________________________________________________________ -->
        <div class="section" id="references">
            <div class="container">
                <div class="col-sm-12">

                    <div class="mb20">
                        <h2 class="title" data-animate="fadeInUp">l'ostéopathie, pour qui ?</h2>
                    </div>

                    <div id="detail">

                        <span class="close">&times;</span>

                        <div class="text-center">
                            <h1 id="detail-title">&nbsp;</h1>
                        </div>

                        <div id="detail-content"></div>

                    </div>
                    <!-- Reference detail -->

                    <div id="references-masonry" data-animate="fadeInUp">

                        <!--  ENCEINTE -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-2.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Femme enceinte</h3>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                    <p>
                                        C'est une période où le corps de la femme est en constante évolution. Prise de poid, changement de posture (courbure lombaire), changement hormonaux peuvent entrainer des déséquilibré du corps 
                                        L’ostéopathe saura détecter les zones de tensions liées à ces différents changements et soulagera les douleurs rencontrées en optimisant une meilleure adaptation du corps à ses changements.

                                        Voici quelques exemples de troubles fonctionnels rencontrés :
                                    </p>
                                        <ul>
                                            <li>Douleur vertébrale</li>
                                            <li>Sciatalgie</li>
                                            <li>Reflux gastro-œsophagien, brûlure gastrique</li>
                                            <li>Douleur coccygienne</li>
                                            <li>Douleur pubienne</li>
                                            <li>Constipation</li>
                                            <li>Troubles circulatoires (jambes lourdes…)</li>
                                            <li>Troubles respiratoires</li>
                                            <li>Stress</li>
                                        </ul>
                                    <p>
                                        En traitant le bassin, les lombaires... l’ostéopathe permet de diminuer les tensions dans le but de faciliter et d’optimiser le bon déroulement de l’accouchement en parallèle d’une préparation classique.
                                    </p>
                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--  NOURISSON  -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-1.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Nourisson</h3>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                        <p>
                                            L'accouchement est le premier évènement qui peut perturber l'équilibre du nourisson. Il est soumis à différents facteur qui peuvent provoquer des tensions : Lors de l’accouchement, le crâne du nourrisson peut subir de fortes pressions notamment lors des contractions utérines ou de l’utilisation d’instruments.
                                        </p>
                                        <ul>
                                            <li>Colique</li>
                                            <li>Régurgitation</li>
                                            <li>Infections à répétition</li>
                                            <li>Troubles du sommeil</li>
                                            <li>Allaitement difficile</li>
                                            <li>Torticolis congénital...</li>
                                        </ul>
                                        <p>
                                            L’ostéopathe repérera les dysfonctions et les corrigera afin de veiller au bon développement du bébé.
                                        </p>
                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--  ENFANT  -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-5.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Enfant</h3>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                        <p>
                                            Les traumatismes répétés (chutes, port du cartable, sport) durant l'enfance peuvent entraîner des conséquences sur l’équilibre du corps pouvant perturber la croissance de l’enfant. Par sa compétence, l’ostéopathe pourra déceler les dysfonctionnements du corps de l’enfant afin de l’aider à son bon développement. Il peut suivre un enfant tout au long de sa croissance et l’accompagner lors des divers traumatismes rencontrés :
                                        </p>
                                        <ul>
                                            <li>Prévention des scolioses</li>
                                            <li>Infections chroniques (ORL…)</li>
                                            <li>Port du cartable</li>
                                            <li>Port d’un appareil dentaire</li>
                                            <li>Sport</li>
                                        </ul>
                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <!--  ADULTE -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-6.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Adulte</h3>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                    <p>
                                        La prise en charge ostéopathique d’un adulte prend en compte la douleur, les antécédents chirurgicaux, traumatiques, pathologiques. Tous ces antécédents peuvent perturber l’harmonie générale du corps (circulation, équilibre, posture…) pouvant provoquer la douleur. Votre ostéopathe prend en compte vos activités quotidiennes (sports, attitudes professionnelles…). Mais il prend aussi en compte les effets que peuvent provoquer le stress quotidien, la fatigue (travail, foyer…). Votre ostéopathe veillera à rétablir l’équilibre général du corps afin de stimuler les capacités d’auto-guérison de celui-ci.
                                        Vous pouvez consulter votre ostéopathe pour :
                                    </p>
                                    <ul>
                                        <li>Douleurs de cou (cervicalgies…)</li>
                                        <li>Douleurs de dos (lombalgies, dorsalgies…)</li>
                                        <li>Sciatiques</li>
                                        <li>Lumbago</li>
                                        <li>Tendinites</li>
                                        <li>Migraines-céphalées</li>
                                        <li>Douleurs musculaires</li>
                                        <li>Douleurs digestives</li>
                                        <li>Brûlures gastrique</li>
                                        <li>Reflux gastro-oesophagien</li>
                                        <li>Après une intervention chirurgicale</li>
                                        <li>Menstruations douloureuses</li>
                                        <li>...</li>
                                    </ul>
                                    <p>
                                        Vous pouvez venir consulter votre ostéopathe dans un but préventif 1 à 2 fois par an afin de maintenir l’équilibre général du corps
                                    </p>
                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>

                            </div>
                        </div>

                        <!--  SENIOR -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-3.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Sénior</h3>
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                    <p>
                                        Le mouvement c’est la vie. Avec l’âge le corps humain perd de façon naturelle en mobilité. Les ligaments perdent de leur élasticité, les cartilages s’usent et s’amincissent. En traitant les dysfonctions de mobilités et donc en améliorant la mobilité générale du corps et la circulation générale du corps, l’ostéopathe peut venir à bout de nombreuses douleurs ou du moins les diminuer.
                                        Les motifs de consultations les plus rencontrés sont :
                                    </p>
                                    <ul>
                                        <li>Sciatalgie</li>
                                        <li>Douleur vertébrale</li>
                                        <li>Difficulté à marcher</li>
                                        <li>Troubles digestifs et urinaires</li>
                                        <li>Troubles du sommeil</li>
                                        <li>Douleurs articulaires</li>
                                        <li>Prévention</li>
                                        <li>...</li>
                                    </ul>
                                    <p>
                                        L’ostéopathie peut vous apporter un certain confort et peut permettre de limiter la prise d’antalgiques et d’anti-inflammatoires.
                                    </p>
                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>

                            </div>
                        </div>

                        <!--  SPORTIF -->
                        <div class="reference-item">
                            <div class="reference">
                                <a href="#">
                                    <img src="img/portfolio-4.jpg" class="img-responsive" alt="" />

                                    <div class="overlay">
                                        <h3 class="reference-title">Sportif</h3> 
                                    </div>
                                </a>

                                <div class="sr-only reference-description" data-images="img/main-slider1.jpg,img/main-slider2.jpg,img/main-slider3.jpg">

                                    <p>
                                        Que ce soit dans le milieu professionnel ou dans le milieu amateur, votre corps est soumis aux traumatismes et microtraumatismes causés par la pratique de votre sport ce qui peut perturber son équilibre généra. L’ostéopathe saura détecter les zones de contraintes afin de rétablir l’harmonie globale du corps et de vous aider à éviter les blessures.
                                        L’ostéopathie dans le milieu sportif est recommandée dans un but préventif :
                                    </p>
                                    <ul>
                                        <li>bilan ostéopathique avant une nouvelle saison sportive</li>
                                        <li>préparation d’une épreuve sportive</li>
                                        <li>amélioration des performances (capacités respiratoires, récupération, puissance…)</li>
                                    </ul>
                                    <p>Egalement, les sportifs peuvent consulter l’ostéopathe après :</p>
                                    <ul>
                                        <li>une entorse (cheville, genou…)</li>
                                        <li>une déchirure</li>
                                        <li>séquelles de fracture</li>
                                        <li>traumatismes</li>
                                        <li>intervention chirurgicale</li>
                                        <li>Douleurs musculaires</li>
                                        <li>Douleurs articulaires</li>
                                        <li>Tendinites (tennis elbow, pubalgies…)</li>
                                    </ul>

                                    <hr>
                                    <div class="text-center">

                                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                                        <p class="buttons">
                                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /#references-masonry -->

                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.section -->

        <!-- *** REFERENCES END *** -->

        <!-- *** ABOUT ***
_________________________________________________________ -->
        <div class="section" id="about">
            <div class="container">
                <div class="row">

                    <div class="col-sm-12">
                        <h2 class="title" data-animate="fadeInDown">À propos</h2>
                    </div>

                    <div class="col-sm-12">

                        <div class="row">
                            <div class="col-sm-6" data-animate="fadeInUp">
                                <img src="img/about.jpg" class="image img-circle img-responsive" alt="This is me - IT worker">
                            </div>

                            <div class="col-sm-6 text-left font-up" data-animate="fadeInUp">

                                <p>
                                    Ma fascination pour le corps humain m'a conduite à en étudier son anatomie ainsi que sa physiologie. C'est ainsi qu'après l'obtention de mon diplôme d'état en <strong>masso-kinésithérapie (école Danhier Paris)</strong> en 2004, je me suis lancée dans les études d'<strong>ostéopathie (école CSO Paris)</strong> pour en obtenir le diplôme en 2010.
                                </p>
                                <br/>
                                <p>
                                    J'exerce actuellement ces deux disciplines conjointement: l'Osthéopathie en début de semaine au centre médical de Provins et la kinésithérapie en fin de semaine à Noisy le Grand (93)
                                </p>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /#about -->

        <!-- *** ABOUT END *** -->

        <!-- *** SERVICES ***
_________________________________________________________ -->
        <div class="section text-gradient" id="services">
            <div class="container">
                <div class="col-md-12">
                    <h2 class="title" data-animate="fadeInDown">le cabinet</h2>

                    <!-- SLIDER -->
                    <div class="sr-only img-slider" data-images="img/centre-medical-1.jpg"></div>
                    <!-- <div class="sr-only img-slider" data-images="img/centre-medical-1.jpg,img/centre-medical-1.jpg,img/centre-medical-1.jpg"></div> -->
                    <div class="col-md-8 col-md-offset-2">
                        <div id="detail-slider"></div>
                    </div>
                    <!-- SLIDER ENDS -->

                    <div class="row services">

                        <div class="col-md-4" data-animate="fadeInUp">
                            <div class="icon"><i class="fa fa-car"></i>
                            </div>
                            <h3 class="heading">Adresse</h3>
                            <p>
                                Le centre médical se trouve à l'adresse suivante <br/>
                                <span class="time">
                                    <b><i>7 avenue de la Voulzie<br/>
                                    </i></b>
                                </span>
                                <span class="time">
                                    <i><b>77160 Provins</i></b>
                                </span>
                                <br/><br/>
                                Ou aux coordonnées GPS suivante:<br/>
                                <span class="time">
                                    <b><i>48.5500328, 3.2948152</i></b>
                                </span>
                            </p>
                        </div>

                        <div class="col-md-4" data-animate="fadeInUp">
                            <div class="icon"><i class="fa fa-plus-square"></i>
                            </div>
                            <h3 class="heading">Centre médical</h3>
                            <p>
                                Le cabinet est idéalement situé dans le nouveau centre médical de Provins.
                                Ce centre regroupe un grand nombre de professionnels de la santé : Matériel paramédical, Centre de radiologie, Opticien, Audioprothésiste etc.
                            </p>
                        </div>

                        <div class="col-md-4" data-animate="fadeInUp">
                            <div class="icon"><i class="fa fa-clock-o"></i>
                            </div>
                            <h3 class="heading">Horaires</h3>
                            <p>
                                Les consultations ont lieu les:<br/>
                                <i class="fa fa-user-md time"></i> Lundis de <strong>10h à 20h</strong><br/>
                                <i class="fa fa-user-md time"></i> Mardis de <strong>9h à 17h</strong>
                            </p>
                        </div>

                    </div>
                    <hr>
                    <div class="text-center">

                        <p class="lead">Vous pouvez vous rendre chez votre ostéopathe <strong>sans ordonance</strong></p>

                        <p class="buttons">
                            <a class="btn btn-primary scrollTo" href="#contact"><i class="fa fa-globe"></i> Prendre RDV</a>
                        </p>

                    </div>
                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.section -->

        <!-- *** SERVICES END *** -->
        <!-- *** MAP ***
_________________________________________________________ -->

        <div class="section" id="map">

        </div>
        <!-- /.section -->

        <!-- *** MAP END *** -->

        <!-- *** CONTACT ***
_________________________________________________________ -->

        <div class="section contact" id="contact" data-animate="fadeInDown">
            <div class="container">
                <div class="col-md-12">

                    <?php if ($this->form()): ?>
                        
                        <h2 class="title">RDV en ligne</h2>

                        <div class="row">

                            <div class="col-md-8 col-md-offset-2">
                                <?php echo $this->form()->openTag($form);?>

                                    <div class="messages">

                                    </div>

                                    <div class="controls">

                                        <div class="row">
                                            <div class="col-md-3">
                                                <div class="input-group">
                                                    <?php echo $this->formElement($form->get('weekDay'));?>
                                                  <span class="input-group-addon"><i class="fa fa-angle-double-down"></i></span>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="input-group">
                                                    <?php echo $this->formElement($form->get('date'));?>
                                                      <span class="input-group-addon"><i class="fa fa-angle-double-down"></i></span>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="input-group">
                                                    <?php echo $this->formElement($form->get('time'));?>
                                                      <span id="icon-time" class="input-group-addon"><i class="fa fa-angle-double-down"></i></span>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <?php echo $this->formElement($form->get('firstname'));?>
                                            </div>
                                            <div class="col-md-6">
                                                <?php echo $this->formElement($form->get('lastname'));?>
                                            </div>
                                            <div class="col-md-6">
                                                <?php echo $this->formElement($form->get('phone'));?>
                                            </div>
                                            <div class="col-md-6">
                                                <?php echo $this->formElement($form->get('email'));?>
                                            </div>
                                            <div class="col-md-12">
                                                <?php echo $this->formElement($form->get('comment'));?>
                                            </div>
                                            <div class="col-md-12 text-center">
                                                <?php echo $this->formElement($form->get('submit'));?>
                                            </div>
                                        </div>
                                    </div>

                                <?php echo $this->form()->closeTag($form);?>
                            </div>

                        </div>
                        <hr>
                    <?php endif ?>
                    <h2 class="title">RDV par Téléphone</h2>

                    <div class="row phone">
                        07.86.07.21.27
                    </div>

                </div>
                <!-- /.12 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.section -->

        <!-- *** CONTACT END *** -->

