<div class="section admin" id="about">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="mb20">
                    <h2 class="title" >Demandes de RDV</h2>
                </div>
                <table class="table table-striped" data-animate="fadeInUp">
                    <thead>
                      <tr>
                        <th>Nom</th>
                        <th>Date</th>
                        <th>Téléphone</th>
                        <th>Details</th>
                      </tr>
                    </thead>
                    <tbody>
                    <?php if (empty($results[\App\Entity\Rdv::STATUS_CREATED])): ?>
                        <div class="col-md-12">Aucun nouveau RDV</div>
                    <?php else: ?>
                        <?php foreach ($results[\App\Entity\Rdv::STATUS_CREATED] as $event): ?>
                            <tr>
                                <td><?php echo $event['firstname'] . ' ' . $event['lastname']; ?></td>
                                <td><?php echo $event['date']; ?></td>
                                <td><?php echo $event['phone']; ?></td>
                                <td><a href="/admin/detail/<?php echo $event['id'] ?>">Details</a></td>
                        <?php endforeach ?>
                    <?php endif ?>
                    </tbody>
                </table>

                <div class="mb20">
                    <h2 class="title" data-animate="fadeInUp">Patient non informé</h2>
                </div>
                <table class="table table-striped" data-animate="fadeInUp">
                    <thead>
                      <tr>
                        <th>Nom</th>
                        <th>Date</th>
                        <th>Téléphone</th>
                        <th>Details</th>
                      </tr>
                    </thead>
                    <tbody>
                    <?php if (empty($results[\App\Entity\Rdv::STATUS_NEED_CONFIRM])): ?>
                        <div class="col-md-12">Aucun nouveau RDV</div>
                    <?php else: ?>
                        <?php foreach ($results[\App\Entity\Rdv::STATUS_NEED_CONFIRM] as $event): ?>
                            <tr>
                                <td><?php echo $event['firstname'] . ' ' . $event['lastname']; ?></td>
                                <td><?php echo $event['date']; ?></td>
                                <td><?php echo $event['phone']; ?></td>
                                <td><a href="/admin/detail/<?php echo $event['id'] ?>">Details</a></td>
                        <?php endforeach ?>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>