<div class="section admin" id="about">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">

                <div class="mb20">
                    <h2 class="title" data-animate="fadeInUp">Demandes de RDV</h2>
                </div>
                <div data-animate="fadeInUp">
                    <?php foreach ($rdv as $event): ?>
                        <div class='col-md-4'>
                            <?php echo $event->firstname . ' ' . $event->lastname; ?>
                        </div>
                        <div class='col-md-4'>
                            <?php echo \App\Services\Date::translate($event->date->format('l d F Y')); ?>
                        </div>
                        <div class='col-md-4'>
                            <a href="admin/detail/<?php echo $event->id ?>">Details</a>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
</div>